---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom-server
  labels:
    app: boom-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boom-server
  template:
    metadata:
      labels:
        app: boom-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - client
            topologyKey: kubernetes.io/hostname
      containers:
      - name: boom-server
        image: anfernee/k8s-issue-74839
        ports:
        - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: boom-server
spec:
  selector:
    app: boom-server
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Pod
metadata:
  name: startup-script
  labels:
    app: client
spec:
  hostPID: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - boom-server
        topologyKey: kubernetes.io/hostname
  containers:
  - name: startup-script
    image: gcr.io/google-containers/startup-script:v1
    command: ['bash', '-c', 'while true; do sleep 2; nc boom-server 9000& done']
    imagePullPolicy: IfNotPresent
